services:
  # Frontend (Simplified)
  frontend:
    image: nginx:stable-alpine
    container_name: carddemo-frontend
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/conf:/etc/nginx/conf.d
      - ./frontend/static:/usr/share/nginx/html
    networks:
      - carddemo-network
    restart: always

  # Database
  postgres:
    image: postgres:14-alpine
    container_name: carddemo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: carddemo
      POSTGRES_PASSWORD: carddemo123
      POSTGRES_DB: carddemo
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - carddemo-network
    restart: always

  # Simplified Auth Service
  auth-service:
    image: openjdk:17-slim
    container_name: carddemo-auth-service
    ports:
      - "8081:8080"
    networks:
      - carddemo-network
    depends_on:
      - postgres
    restart: always
    command: >
      sh -c 'echo "Auth Service is running on port 8080" && sleep infinity'

networks:
  carddemo-network:
    driver: bridge

volumes:
  postgres-data: